# Generated by Django 3.2.7 on 2021-10-17 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210915_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessagesLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_message_send', models.BooleanField(default=False)),
                ('lessons_passed', models.IntegerField(default=0)),
                ('is_last_lesson_was_yesterday', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.students')),
            ],
        ),
    ]
