# Generated by Django 3.2.7 on 2021-10-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_sendmessageslog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sendmessageslog',
            options={'verbose_name': 'Лог отправки сообщений', 'verbose_name_plural': 'Лог отправки сообщений'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterField(
            model_name='sendmessageslog',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания записи'),
        ),
        migrations.AlterField(
            model_name='sendmessageslog',
            name='is_last_lesson_was_yesterday',
            field=models.BooleanField(default=False, verbose_name='Последний урок был вчера? Да,нет'),
        ),
        migrations.AlterField(
            model_name='sendmessageslog',
            name='is_message_send',
            field=models.BooleanField(default=False, verbose_name='Сообщение отправлено? Да,нет'),
        ),
        migrations.AlterField(
            model_name='sendmessageslog',
            name='lessons_passed',
            field=models.IntegerField(default=0, verbose_name='Количество пройденных уроков'),
        ),
    ]
